services:
  # Redis Exporter
  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      # Docker Desktop 환경(Mac/Windows)에서 호스트 PC의 6379 포트로 접속하는 특수 주소입니다.
      - REDIS_ADDR=redis://host.docker.internal:6380
    ports:
      - "127.0.0.1:9121:9121"

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"

  # Grafana (시각화 대시보드)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
